version: '3'
services:

 postgres:
  image: postgres:${POSTGRES_VERSION}
  restart: "on-failure"
  environment:
   POSTGRES_DB: ${POSTGRES_DB}
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  volumes:
   - pg_data:/var/lib/postgresql/data
  healthcheck:
   test: ["CMD", "ps_isready", "-U", "${POSTGRES_USER}"]
   timeout: "5s"
   retries: "5"

 kong:
  image: marcelmaatkamp/kong-with-plugins:${KONG_VERSION}
  build:
   context: .
   args:
    KONG_VERSION: ${KONG_VERSION}
  depends_on:
   - postgres
  environment:
   KONG_DATABASE: "postgres"
   KONG_PG_HOST: "postgres"
   KONG_PG_DATABASE: "${POSTGRES_DB}"
   KONG_PG_USER: "${POSTGRES_USER}"
   KONG_PG_PASSWORD: "${POSTGRES_PASSWORD}"
   # KONG_PLUGINS: "bundled,oidc,amqp,kong-kafka-log"
   KONG_PLUGINS: "bundled, kong-upstream-jwt"
   KONG_PROXY_LISTEN: 0.0.0.0:8000
   KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
   KONG_ADMIN_LISTEN: 0.0.0.0:8001
   KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: "16 256k"
   KONG_NGINX_PROXY_PROXY_BUFFERS: "4 256k"
   KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: "128k"
  ports:
   - 80:8000

 konga:
  image: pantsel/konga:0.14.9
  restart: always
  environment:
   NODE_ENV: production
   DB_ADAPTER: postgres
   DB_HOST: postgres
   DB_DATABASE: "${POSTGRES_DB}" 
   DB_USER: "${POSTGRES_USER}"
   DB_PASSWORD: "${POSTGRES_PASSWORD}"
   TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
  depends_on:
   - postgres
   - kong
  ports:
   - "1337:1337"

volumes:
 pg_data:
